Repository minisbett/epiclonvisualizer, pull requests merged in 2024-03, with the labels that each got.

#1 chore: remove makefile
  Makefile
Labels: chore

#2 chore: move pyinstaller.spec file to ext folder
  .github/workflows/publish.yml
  ext/pyinstaller.spec
Labels: chore

#4 feat: add icon for the executable file
  ext/icon.ico
  ext/pyinstaller.spec
Labels: feature

#6 refactor: move `HotkeyEvent` to `objects/hotkey_event.py`
  main.py
  objects/hotkey_event.py
Labels: refactor

#8 refactor: rename executable (add version) before artifact upload
  .github/workflows/publish.yml
  ext/pyinstaller.spec
Labels: refactor

#9 feat: add update checker
  .github/workflows/publish.yml
  ext/pyinstaller.spec
  ext/requirements.txt
  main.py
Labels: feature

#10 fix: echo in version.txt with wrong syntax
  .github/workflows/publish.yml
Labels: fix

#15 chore: changed config value names in readme
  README.md
Labels: chore

#16 chore: updated release url
  main.py
Labels: refactor

#17 feat: added "ctrl+o" to default keybinds
  config.py
Labels: feature

#18 feat: added bookmark shortcuts default keybinds
  config.py
Labels: feature

#25 refactor: restructure the app code, allowing better maintainability
  app/config.py
  app/handlers/hotkey_handler.py
  app/handlers/web_handler.py
  app/logging.py
  app/utils.py
  main.py
  objects/hotkey_event.py
Labels: refactor

#26 fix: make logging support ANSI colors on conhost-based consoles
  app/config.py
  app/handlers/hotkey_handler.py
  app/handlers/web_handler.py
  app/logging.py
  app/utils.py
  ext/requirements.txt
  main.py
Labels: bug

#29 feat: add option for maximum simultaenously displayed keys
  app/config.py
  static/js/visualizer.js
  templates/visualizer.html
Labels: feature
